baseURL: "https://hockeyguy123.github.io/" 
title: Amir Sadikov
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
params:
    description: "This website hosts Amir Sadikov's research papers, curriculum vitae, and contact information."
    author: Amir Sadikov
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Amir Sadikov
          subtitle: "I am a PhD candidate in the Joint UC Berkeley & UCSF Bioenginerring Program, under the supervision of Dr. Pratik Mukherjee. I perform research at the intersection of AI, neuroscience, and imaging."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:amirasadikov@gmail.com
        - name: GitHub
          url: https://github.com/hockeyguy123
        - name: Linkedin
          url: https://www.linkedin.com/in/amir-sadikov-045708133/
        - name: orcid
          url: https://orcid.org/0000-0002-0253-3543
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Amir Sadikov"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
